on:
  push:
    branches:
      - hotfix/**

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .hotfix-release-please-config.json
          manifest-file: .release-please-manifest.json
