name: Send Changelog to Discord

on:
  release:
    types: [published]

jobs:
  send-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Read CHANGELOG.md
        id: changelog
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "content=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚀 **Nouvelle Release**: ${{ github.event.release.tag_name }}

            **Changelog:**
            ```md
            ${{ steps.changelog.outputs.content }}
            ```

            [Voir la release sur GitHub](${{ github.event.release.html_url }})
